
#Configuración sin utilizatr Spring Config

# Spring properties
# spring:
#   application:
#      name: location-service  # Service registers under this name
# Discovery Server Access
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:1111/eureka/

# HTTP Server
# server:
#   port: 3333   # HTTP (Tomcat) port

#spring:
#  application:
#    name: location
#  cloud:
#    config:
#      uri: http://localhost:8888


spring:
  application:
    name: location-service  # Service registers under this name
server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5